### ISSUE TITLE
game window size bigger than expacted

### ISSUE THREAD

**Issue by sirlis** [renpy/renpy#1015]
os: win10  &  win7
latpop screen resolution: 1920 \* 1080
game resolution: 1280 \* 720

however, game in window will not be exactly the size that 720p will be in 1080p. In fact, the actual game window size is roughly 125% bigger than normal 720p as is shown in figure below.
But i don't know the exact size because i don't measure it.

In the figure, the screen is 1920*1080, the red rectangle is 1280 \* 720 as a wallpaper, the actual game window is bigger than the red rectangle.

![1](https://cloud.githubusercontent.com/assets/12960298/17853572/ef2f2238-689f-11e6-9bf9-632116567bff.png)

**Comment by sirlis** [comment]
I run the game from renpy launcher and from my windows distribution exe file, both of which has the same size problem.

**Comment by renpytom** [comment]
Which version of Ren'Py are you using? I think this has been fixed in 6.99.11.

**Comment by sirlis** [comment]
I check renpy for update but I failed to get the 6.99.11 version. 
my version is 6.99.10.1227 and when i click update on the launcher it still get 6.99.10.1227 available.
I don't know how to solve it.

**Comment by sirlis** [comment]
My renpy version is 6.99.10.1227 I check renpy for update but I failed to get the 6.99.11 version. my version is 6.99.10.1227 and when i click update on the launcher it still get 6.99.10.1227 available.I don't know how to solve it.
Date: Mon, 22 Aug 2016 17:46:45 -0700

**Comment by sirlis** [comment]
![1](https://cloud.githubusercontent.com/assets/12960298/18129351/01f190c6-6fbd-11e6-9092-b2524d500e8b.png)
![2](https://cloud.githubusercontent.com/assets/12960298/18129353/033e99b0-6fbd-11e6-9e3a-c872e0e8bb65.png)

**Comment by pratomoastan** [comment]
Maybe you must change your update channel to nightly .

Pada tanggal 31 Agt 2016 19.53, "sirlis" <notifications@github.com> menulis:
