### ISSUE TITLE
rollback not preserving variables as before

### ISSUE THREAD

**Issue by jacknorton** [renpy/renpy#1414]
I'll try to see if I can put a demo, but I'm pretty sure the rollback doesn't work as before. For example a simple call to a label like this:
```
label job_viktorlines:
    #random number generator
    $RN=renpy.random.randint(0,5)
    #then each of these lines gets a number and plays at random when you do this job.
    if RN==0:
        "You donned what appeared to armored hazmat suits when Viktor announced today was the day you would reclaim the storage closet from the dust bunnies."
    if RN==1:
        "Every time you counted chemical bottles, the number kept increasing.  After the tenth incident of this, Viktor said that a gremlin was probably loose in the lab and pay it no mind."
    if RN==2:
        "You and Viktor went to a new site today, only to quick retreat when the radiation meter went off the chart.  The two of you underwent a decontamination procedure, which Viktor promised would reduce the chances of developing an extra limb by 90%%."
return
```
if I hit shift+R while the game is running and I try to rollback, it crashes not remembering the value of RN  with:

```
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scheduler.rpy", line 411, in script call
    call expression (slines2) from _call_expression_5
  File "game/oneliners.rpy", line 22, in script
    if RN==2:
  File "game/oneliners.rpy", line 22, in <module>
    if RN==2:
NameError: name 'RN' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scheduler.rpy", line 411, in script call
    call expression (slines2) from _call_expression_5
  File "game/oneliners.rpy", line 22, in script
    if RN==2:
  File "C:\- indie dev -\games\renpy\renpy\ast.py", line 1702, in execute
    if renpy.python.py_eval(condition):
  File "C:\- indie dev -\games\renpy\renpy\python.py", line 1843, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\- indie dev -\games\renpy\renpy\python.py", line 1836, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/oneliners.rpy", line 22, in <module>
    if RN==2:
NameError: name 'RN' is not defined

Windows-7-6.1.7601-SP1
Ren'Py 6.99.14.1.3218
Love Bites 0.7
Sun Mar 25 09:42:59 2018
```
Before this was working 100% of the times (I know because it's the same system used in Roommates and never had a bug like this). I think it happens for all variables in rollback, including ones passed to variables or even screens.

**Comment by renpytom** [comment]
I'm pretty sure this was fixed by 0572210e2ec891e60ff1078ec390f144f10bcb61.

**Comment by jacknorton** [comment]
Sadly I just updated to the latest version and the bug still remains. I load a save and rollback, and I get the same traceback for variables that surely are defined :( thanks

**Comment by renpytom** [comment]
Can you repeat the bug without using the old version? It's possible for this bug to be "baked in" to save, but it shouldn't happen in the new version.

**Comment by jacknorton** [comment]
Ah OK. I tried to start a new game with the new version and it seems to work so far :)

**Comment by jacknorton** [comment]
Hmm there's definitely something weird going on. I tried starting a new game with latest Ren'Py. After a while I was editing a screen using reload, I got that crash again. Not just that but if I clicked ignore, the game would go on with the female character, so somehow the variable got changed, but the init block by default is the male one. So how it got selected the female is a big mystery.
I am 99% sure that there's still something wrong regarding variables and rollbacks. maybe happens only if you are in "auto reload" mode though.

**Comment by jacknorton** [comment]
I did more testing and I think it's not the rollback, but the default/init issue we talked with chat before.
Example: I have a variable to se if character is male or female. like in all other games, I have in a init block:
$ male = False
(using by default the female character).
then at start of the game I have a screen to select the gender called like this:
```
label char_select:
    scene green
    $brandon_cloth="casual";brandon_stage=1;brandon_pose=1
    $kaitlyn_cloth="casual";kaitlyn_stage=1;kaitlyn_pose=1
    $Chosen=""
    call screen choose_char

    if Chosen==0:
        $ he="he";his="his";him="him";He="He";His="His";mainc="i_brandon";pname="Brandon Lawrence";rpgc="brandon";spn="Brandon";sir="sir";Sir="Sir";boy="boy";man="man";sister="sister";other="Kaitlyn Lawrence";
        $ male = True
    else:
        $ he="she";his="her";him="her";He="She";His="Her";mainc="i_kaitlyn";pname="Kaitlyn Lawrence";rpgc="kaitlyn";spn="Kaitlyn";sir="ma'am";Sir="Ma'am";boy="girl";man="woman";sister="brother";other="Brandon Lawrence";
        $ male = False
    $ save_name = "Prologue";genhelp=0
    return
```
the problem is, if I remove the init and put "default male = False" even if I load a save where I picked the male, the character shown is female. So it's like if the male variable is not saved properly. I works differently than all previous renpy versions for sure, since I never had to use the default keyword before, always used init and then setting the variable in the main code $var=value and it always worked. Now in this latest version it's no longer working like before.
