### ISSUE TITLE
Temporary say attributes sometimes stick

### ISSUE THREAD

**Issue by mal** [renpy/renpy#1725]
Script covers it, but using a temporary say attribute "sticks" when it should revert to the default on `7.1.4-pre`.

```renpy
label main_menu:
    $ _confirm_quit = False
    pass

layeredimage alice:
    always:
        Text('always', yoffset=-20)
    group A:
        attribute alpha default Text('alpha')
        attribute beta Text('beta')

define alice = Character('Alice', image='alice')

label start:
    show alice at Position(pos=(.25, .5)) with dissolve
    alice 'We start with alpha, the default.'
    alice @ beta 'Then use beta as a temp say attr.'
    alice '... beta "sticks", rather than reverting to the default: alpha! D:'
```

**Comment by renpytom** [comment]
I believe this has been fixed by 15cf4341c34298b578bb1e6d375db7659d8fd51a .

**Comment by mal** [comment]
@renpytom can still reproduce this on latest `master` (https://github.com/renpy/renpy/commit/2b0691233e63f40940dc6d2e838c962172d392b7).

**Comment by renpytom** [comment]
Fixed this with a slightly different fix.
