### ISSUE TITLE
Rolling back causes the caption in menu to not appear

### ISSUE THREAD

**Issue by trajano** [renpy/renpy#1930]
I'll make a tester for this later.

At the moment I have

```
   menu:
        n "How do you like the dialog boxes? Its Perona 4 style and it works well for portait mode"
        "I like it":
            n "Glad you like it.  I like it too"
        "Needs work":
            n "Yah, just give it time, you'd get it to the way you like it."
````

When I rollback the caption does not appear but only if it is the first `menu` (i.e. no other dialog before)

**Comment by renpytom** [comment]
What version are you on? This was fixed recently (in one of the 7.3 releases), but you'll need to force recompile your game to get the fix.

**Comment by trajano** [comment]
OK let me check.  I am on the current release afaik

**Comment by trajano** [comment]
Just tested right now, still have the issue after I did an update from the RenPy and forced recompile

So sequence I had was 

choose an item
play a couple of dialog
press the back button until the select shows.

**Comment by Gouvernathor** [comment]
Can't reproduce, this was probably fixed.
