### ISSUE TITLE
Audio playback causes in-game stuttering

### ISSUE THREAD

**Issue by morganwillcock** [renpy/renpy#2024]
It looks like some aspect of audio playback is blocking the main thread and causing the game to freeze momentarily. For me the problem is easy to recreate by playing the Pong mini-game in the tutorial.

I've attached a recording:
[capture.zip](https://github.com/renpy/renpy/files/3687384/capture.zip)
...it doesn't manage to quite capture the degree of stuttering that I see, but hopefully there are a few instances here where it is obvious that the ball and bats freeze shortly after the ball touches something.

The gap between the audio being played and the stutter can sometimes be quite large, usally about half a second after the playback has finished.

If the commands for audio playback are commented out then the game plays with no stuttering.

**Comment by renpytom** [comment]
Can you give me a bit more information about your computer, please? I've been looking at this on my Windows and Linux boxes, and I can't actually repeat the stuttering here. I've also audited the various code paths, and it doesn't look like Python code runs inside the pong system. I'm curious if this is a marginal computer or something new. 

Also, could you hit f3, to display the framerate counter, his performance, and see what the framerate and max frametime do during this stuttering? That would also be helpful. 

Thank you!

**Comment by morganwillcock** [comment]
Thanks for looking into this. The computer is a Thinkpad T520, Core i7-2620M 2.70GHz (dual core with hyperthreading disabled), 8GB of RAM, Windows 10.0.18362.356. The graphics are split between Intel HD3000 and an Nvidia NVS 4200M (I can launch an application with either).

I've been trying to narrow down what causes it and it seems specifically related to using the Nvidia graphics, which is also the default when using an external monitor as the main display (which I am most of the time). I've updated the driver to see if it makes a difference, but it didn't seem to. So I thought that maybe the issue could be caused by my low CPU core count and some kind of threading change caused by the driver, which lead me to this:

https://stackoverflow.com/questions/36959508

So I disabled "Threaded Optimization" in the Nvidia control panel, and now the problem is gone.

>Also, could you hit f3, to display the framerate counter, his performance, and see what the framerate and max frametime do during this stuttering?

When it stutters the FPS drops into the 40s, I've definitely seen it go as low as 45. The maximum frame time can get as high as 62ms (smaller increases can also occur, but I've not seen it jump higher than this).

It doesn't look like there is a way for a game to flag itself to not be automatically 'optimized'. For me the difference between the two is pretty jarring, but possibly with more CPU cores other people are seeing a tamer version of the same issue (just going by one other person's feedback, where they said they could see a small stutter).

**Comment by renpytom** [comment]
I'm not sure what I can do about this. The "solution" given in the stack overflow example would require an installer, which I don't want to add to Ren'Py games. I'm also not sure this would be an improvement on more capable computers. 

You can possibly type shift+G, and enable Tearing, that might mask the problem. It also may be possible to enable DirectX mode, which would probably avoid the problem entirely. Fundamentally, though, I don't think Ren'Py is doing anything wrong here, and so I don't really see anything that I can fix that wouldn't do more harm  than good.

**Comment by morganwillcock** [comment]
That's fine, it seems like an external issue that is probably system specific too.

If there was somewhere on the website that had some information for general performance problems (rather than being labelled as [display problems](https://www.renpy.org/doc/html/display_problems.html)), maybe just documenting this driver feature would be enough to close the issue.

**Comment by fblampe** [comment]
We have also been experiencing this issue, especially when playing very short sounds to simulate character voices.
Thanks for the hint about Direct X, choosing that is a workaround!

**Comment by JellySnek** [comment]
Hello! This is still an issue, thought I'd comment. Indeed disabling "Threaded Optimisation" in Nvidia control panel, allievates the issues on OpenGL renderer, actually not forcing us to use DirectX. We use 7.3.5, but it also happened on 7.4.2 x64 and x86 respectively.

**Comment by morganwillcock** [comment]
> My suggestion would be to force engine to turn off threaded optimisation somehow, like osu! does, then turn it back to last known value once game is closed. Also adding relevant option to Shift + G menu where we can disable this feature.

I had a quick search, I guess it is using this:
https://docs.nvidia.com/gameworks/content/gameworkslibrary/coresdk/nvapi/group__drsapi.html

**Comment by Tapirismus** [comment]
Hello everyone.
I want to add, that this does not seem to be an Nvidia exclusive problem, as I have the same issue on two laptops with AMD graphics cards. Some code, that executes constant Audio playback during dialogue(Text bleep) caused these issues for me. AMD does not have the "Threaded Optimisation" option in its settings unfortunately and Enabling DirectX does also not seem to solve the problem for the AMD machines. Which makes this quite a problem, as there does not seem to be a workaround.

**Comment by morganwillcock** [comment]
It might not be the same problem, you can get similar issues if anything blocks the main update process. e.g. for older versions of renpy it has already been an issue: https://github.com/renpy/renpy/issues/1174

So maybe there are other problems, but the one identified here seems very specific to Nvidia driver settings and OpenGL, and also is not renpy specific.

**Comment by renpytom** [comment]
I believe I've addressed the nvidia problem, by writing something that uses the DRS api to disable the threaded optimization setting. 

With the text beep thing on AMD, please make sure that you have a long enough audio file. Ren'Py is not meant to play back audio files of less than a few seconds in length - the longer files give time to queue in the next file to prevent stuttering.

**Comment by Tapirismus** [comment]
> With the text beep thing on AMD, please make sure that you have a long enough audio file. Ren'Py is not meant to play back audio files of less than a few seconds in length - the longer files give time to queue in the next file to prevent stuttering.

Unfortunately,  making the audio files longer did not seem to resolve the issue. This is the code in question, that causes these issues for me: [https://lemmasoft.renai.us/forums/viewtopic.php?f=8&t=38325&start=15](url) (the one that is written by TamaYoshi, that plays the Text Bleep per Character.)
Thank you for everyones time

P.S.: As Morgan has mentioned, I'm not sure if this is still related to the original problem. I really did not want to derail this discussion.

**Comment by renpytom** [comment]
I believe the nvidia problem is fixed in the nightly. 

I don't think the other problem is actually a problem. It seems to be using timers to play audio files many times a second, something that isn't really a supported case.

**Comment by morganwillcock** [comment]
Was the fix for this to turn off the threaded optimization globally for every application?

It seems to be generating bad press:

> One word of warning, and this seems to be a common bug. The RenPy installation changes a setting in the NVIDIA control panel that will result in No DC being displayed in the top left corner of Godot or Blender.

-- https://gamefromscratch.com/renpy-visual-novel-game-engine/

**Comment by renpytom** [comment]
It's restored when Ren'Py exits. Fundamentally, the right solution is for Nvidia to fix their problem, but I think this is the best workaround I could find.

**Comment by Squall-Leonhart** [comment]
> It's restored when Ren'Py exits

Clearly it isn't, and no, the right solution is for you to not be touching the Global configuration, use the NVAPI to insert your own profile and change that.

**Comment by SanderBouwhuis** [comment]
Please fix this bug!
Everyone is having trouble with this.
