### ISSUE TITLE
entry point (_main) undefined. for architecture arm64

### ISSUE THREAD

**Issue by ikusorae** [renpy/renpy#2385]
![image](https://user-images.githubusercontent.com/60040734/95077494-8ed37b80-074e-11eb-9416-1aa873ec3b26.png)

![image](https://user-images.githubusercontent.com/60040734/95077522-972bb680-074e-11eb-9f23-0efb0bc15b42.png)

In nightly builds with Xcode 12, the build fails with the error when testing through the iOS device.

**Comment by nimalouk** [comment]
not only in nightly builds, also in the stable version.

**Comment by renpytom** [comment]
I believe this should be fixed in 7.4.

**Comment by CrazyPeter** [comment]
I am using version 7.4.4, but this problem still exists. It seems that less runtime is configured in it. @renpytom

**Comment by feliperezende** [comment]
I'm having the same problem on 7.4.4

**Comment by renpytom** [comment]
Can you try the 7.4.5 nightlies?

**Comment by renpytom** [comment]
This is now being tracked as #2745  .
