### ISSUE TITLE
Android export does not work on macOS. (add)

### ISSUE THREAD

**Issue by ikusorae** [renpy/renpy#2511]
I'm using the recently updated macOS big sur 11.1.

Android export does not work on all versions, including Stable 7.3.5 and nightly build.
If I attempt to export Android with a completely new Ren'py, it stops where the 'I'm compiling a short test program, to see if you have a working JDK in your system.' sentence appears.
And If I use Ren'py which previously worked well with Android export, it just stops at the stage where it use Gradle.
It worked well in Catalina, so I suspect it might be a problem with Big sur 11.1.

Or am I wondering if this is a problem with my mac environment.
Thank you always for your hard work.

**Comment by ikusorae** [comment]
https://lemmasoft.renai.us/forums/viewtopic.php?f=8&t=60862&p=537379&hilit=mac#p537379
I found someone complaining of a similar problem. It seems likely that the problem is related to big sur.

**Comment by renpytom** [comment]
I believe this has been fixed by renpy/renpy-build@a5f4feb2a0b6fb81460aa14463bbc89d7bc980e4 .

**Comment by ikusorae** [comment]
I think it still doesn't seem to work. It still stops at the 'I'm compiling a short test program, to see if you have a working JDK in your system.' stage.

**Comment by renpytom** [comment]
I believe this has been fixed in the 7.4 releases.
