### ISSUE TITLE
Sound and Music Volume reset on load and rollback

### ISSUE THREAD

**Issue by Phalzyr** [renpy/renpy#2654]
I am using the volume parameter when playing sounds on version 7.40 (just dloaded latest version), and some music I play at 0.1 volume since orig file is loud, and it work fine until i rollback or load a game then it is full blast again. Is this a known issue I didn't see anything in search...?

**Comment by Phalzyr** [comment]
Also note that if in replay and get out the menu music reset to full volume (I set it in "label before_main_menu:")

**Comment by Archy812** [comment]
Same here, test:

`
label start:
    $ renpy.music.play("/audio/engine.ogg", loop=True, relative_volume=0.25)

    "1"

    "2"

    "3"

    jump start
`


[engine.zip](https://github.com/renpy/renpy/files/6132298/engine.zip)

**Comment by Phalzyr** [comment]
Something else sound related I noticed is that when in a gallery replay mode a sound is looped, when you click end replay the sound continues to loop... easy to work around but...

**Comment by AndriWilford** [comment]
I believe this would be solved by changing

https://github.com/renpy/renpy/blob/32494c4577a2143e10558238e4cc1bf1ae267409/renpy/audio/audio.py#L1177

To looks like

`c.enqueue(filenames, loop=True, synchro_start=True, tight=tight, fadein=renpy.config.context_fadein_music, relative_volume=ctx.tertiary_volume)`

**Comment by AndriWilford** [comment]
Above isn't quite correct..

I believe:
1)  last_filenames is *only* set to the *last* queued call that has  loop=true ,  so although one can call something like
```
play music "song.ogg" loop volume 0.7
renpy.music.queue(["more.ogg, evenmore.ogg"], channel="music", loop=True,  relative_volume=0.4)
renpy.music.queue(["final.ogg, evenmorefinaller.ogg"], channel="music", loop=True,  relative_volume=0.1)
```
   ... the last_filenames will be set to   ["final.ogg, evenmorefinaller.ogg"]  and only that will actually loop (and be the only tracks restored on a context restore)

2) The sound channel's context has the tertiary volume saved when the *current* track is played, so is set to the *currently* playing file's relative volume (So, not the last items to loop in the current queue). This means that, for instance, if the last playing track was "more.ogg"  in the example above,  last_filenames would be  ["final.ogg, evenmorefinaller.ogg"]   but the context would be storing  a tertiary volume of  0.4 ,  not 0.1

Perhaps this is solved by having a  "last_tertiaryvolume"  or something that is saved in the context as well, around:
https://github.com/renpy/renpy/blob/92cae359544b98bc698eb41103d0ea5d12b74e31/renpy/audio/music.py#L133-L138
 .. and ..
 https://github.com/renpy/renpy/blob/92cae359544b98bc698eb41103d0ea5d12b74e31/renpy/audio/music.py#L227-L232
 
 .. and then restoring it in the context restore like
 
 ```
                filenames = ctx.last_filenames
                tight = ctx.last_tight
                relativevolume = ctx.last_relativevolume   #<--------

                if c.loop:
                    if not filenames or c.get_playing() not in filenames:
                        c.fadeout(renpy.config.context_fadeout_music or renpy.config.fade_music)

                if filenames:
                    c.enqueue(filenames, loop=True, synchro_start=False, tight=tight, fadein=renpy.config.context_fadein_music**, relative_volume=relativevolume**)   #<--------------  changed last parameter

                c.last_changed = ctx.last_changed
```

**Comment by Mirgosoft** [comment]
Yeah, solved with just adding to renpy\audio\audio.py:

1) In the MusicContext class:
``` 
   # What were the filenames we were ordered to loop last?
   self.last_filenames = [ ]

   self.last_relative_volume = 1.0     # <---  This

   # Should we force stop this channel?
   self.force_stop = False
   ```
2) In  def interact()  (added last agument relative_volume=ctx.last_relative_volume ):
```
    if filenames:
        c.enqueue(filenames, loop=True, synchro_start=True, tight=tight, relative_volume=ctx.last_relative_volume) 
```
3) And in renpy\audio\audio.py  in 2 same places (play() and queue() funcs) add:
```
    if loop:
        ctx.last_filenames = filenames
        ctx.last_tight = tight
    else:
        ctx.last_filenames = [ ]
        ctx.last_tight = False

    ctx.last_relative_volume = relative_volume  # <--- This.
```
And It's resolve any my problems with cases:
- After load the game.
- After reloading scripts on Shift+R.
- Maybe something else)

Using renpy 7.3.5.

**Comment by ksiadz** [comment]
Hi, I believe in some cases this still happens. 

I added UI sound on all buttons I have, it works on all except for Rollback one. 

The way I added it:
`imagebutton auto "gui/button/back_%s.png" action [Play("sound", "audio/licensed/XXX.ogg"), Rollback()] xpadding -3`

It's not a biggie, but I am raising it just for you to know.
