### ISSUE TITLE
Preference("rollback side") does not work on mobile

### ISSUE THREAD

**Issue by raspberry-soft** [renpy/renpy#3130]
Changing the `Preference("rollback side")` option in the preference screen on a new game does not change the rollback side on Mobile emulation. Tested in a 1080p game using 7.4.10 and 7.4.11. I believe I had this problem since many versions ago.

Using `SetField(preferences, "mobile_rollback_side", "left")` fix the problem, but it would be nice if `Preference("rollback side")` automatically change this variable when on mobile.

I apologize if this works as intended but the documentation states:

- `preferences.mobile_rollback_side` : This is the equivalent of the "rollback side" preference when on a mobile platform.

Also, running `gui.rebuild()` fix it too by synchronizing the Preference action and the mobile variable, which previously weren't.

As a side note: running `gui.rebuild()` when on mobile restore the desktop gui which is a problem. (I know why, because it reruns the define statements). I would like a way to rebuild the gui in mobile without it reverting to the desktop format out of the box. My only guess is by putting all gui variables in an init block so they don't rerun. New users may find it as a problem like I did (I couldn't figure it out until I learned Python and dug through the documentation)

**Comment by renpytom** [comment]
The first half is addressed in 1098d03a04bc4b2a8aa48a29601c3062a77cd808 , the second in 40ea46a9384312cc351a0a74455514a63b9d9ad5 .

**Comment by raspberry-soft** [comment]
As of  Nov-18 nightly (7.5.0.86n): 

- The first half bug still persist.
- The second half is fixed when tested with a new project, although some gui variables I defined with the decorator `@gui.variant` are not working when they did before with `renpy.variant("mobile")`. But I suspect it's due to the gui architecture of my project so I have to figure out where are the problems.

**Comment by renpytom** [comment]
I believe this is entirely fixed by 38a19308e3c0316e84bfe424615898f08ab20488 .
