### ISSUE TITLE
Frequent Crashes on Mobile Ports

### ISSUE THREAD

**Issue by DarkChibiShadow** [renpy/renpy#3643]
I upload my games to Google Play and my crash reports have gotten very out of hand the last year or so. 

Most of my games have about an 4%-8% crash rate. This seems to be the average on any app that uses Ren'py and is uploaded to Google Play. (I've spoken to 2 other users who use Ren'py to port to mobile who have reported similar findings.)

The issues reported are either:
-The game opens, plays a few lines of dialogue, before going black and crashing completely.
-The game never opens, or when it does open, it's a black screen.

Most crashes seem to happen with Android 11, by a long shot.
Here's a few devices we've seen crashes on: LGE K22, Samsung Galaxy A70, LGE LG K30, Samsung Galaxy JG+, Samsung Galaxy A51, Samsung Galaxy A11, Samsung Galaxy A10e, Motorola Moto E20, Vsmart Hobson, Samsung Galaxy A03 Core, Samsung Galaxy J7, and many, many more. Maybe these devices all have something in common?

![image](https://user-images.githubusercontent.com/77140159/173161446-7cf8b021-87da-4e8e-9eb8-ca9b2937dba7.png)
![image](https://user-images.githubusercontent.com/77140159/173161560-65340cc1-dc35-4d67-89c9-a2a95dcb9a3e.png)

These crashes disproportionately affect users who are not using the default language of English. 

We have tried "banning" certain devices that have enough crashes to warrant this, but the crashes can be so inconsistent that sometimes we could be banning phones where over half of the users can still play the game. It's gotten so bad that about a third of my reviews are just about this crash (meaning a good chunk of my reviews are now just 1 star because of this problem, oof) and it makes me very worried about future mobile releases. Mobile releases are the life blood for most smaller visual novels like mine, so it's very important to me that they're working.

If nothing can be done about this, I'm going to keep a public list of devices that are **known** not to be compatible with Ren'py anymore. That way, people can at least exclude them from the releases to help avoid this crash and review problem. 
Forgive me if I'm not able to submit a detailed enough report, I'm putting this here in the hopes someone with more knowledge and time can fill in some of the gaps. Thanks for your time!

**Comment by renpytom** [comment]
This isn't a useful issue, as it is. 

I need to know specific games with this problem, the version of Ren'Py those games were released with, and ideally crash dumps from devices that are having the problem.

**Comment by DarkChibiShadow** [comment]
I understand, and that's why I was hoping more people would chime in with better information. I have no idea how to get a crash dump from a device. I'm very sorry.

Here are some games I know are affected:
https://play.google.com/store/apps/details?id=liars.maze&hl=en_US&gl=US
https://play.google.com/store/apps/details?id=com.darkchibishadow.tomai
https://play.google.com/store/apps/details?id=com.darkchibishadow.solanaceaeat
https://play.google.com/store/apps/details?id=com.touchtheory.darkchibishadow
https://play.google.com/store/apps/details?id=com.mintglow.puqffal
https://play.google.com/store/apps/details?id=com.mintglow.sweetlysweetenedsweets

I can see something like this on GP that's called a "stack trace" but otherwise my information seems to be very limited:

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 0 >>> com.darkchibishadow.tomai <<<

backtrace:
  #00  pc 000000000059168c  /data/app/~~QmR-uniiSwx_XMKUhFulKg==/com.darkchibishadow.tomai-a-CA9R_Rkil_PeVN4rnYGg==/lib/arm/librenpython.so
  
At least 2 games with this crash issue have been exported to mobile with 7.4.11, however, multiple of the games were made in Ren'py well before the 7.4 release. (The games got updated with translations, so got re-exported.)

Give me some time and I will try to get better information. Again, my apologies.

**Comment by MintGlow** [comment]
Hello,
I've also been experiencing this issue with Google Play, and I have used Ren'Py 7.4.11 to port to a .aab file.

https://play.google.com/store/apps/details?id=com.mintglow.puqffal <- is my most recent one, and someone very recently left a review about it kicking them out "every 4-5 minutes" despite the updates and optimizations I attempted to make. 

I had originally made and ported the game in Ren'Py 7.4.9, which also had users crashing.

On the receiving end of it, I first encountered this issue with https://play.google.com/store/apps/details?id=com.darkchibishadow.solanaceaeat made with Ren'Py. At first, it worked fine, but when I left the game and reopened/refreshed it, it became a black screen. Unfortunately, I tried but cannot recreate the crashes.

I also second the fact that these issues seem to mainly be happening with Android 11 (actually, they have **_only_** happened with Android 11 on my games). I also do not know how to get a crash dump either at the moment... If there's any other information you might need, I would like to try to obtain it.

**Comment by Org-gith** [comment]
I have also noticed an increase in crash reports from android users on my end, overall there seem two types of crash report:
- They start the app/click on start the game and the application crash right away, every time I ask for their phone specs, and they would tell me the specs of a device that is clearly very old, unfit for the task. That type of crash didn't increase/decrease, so they are normal I think, just means the phone ain't powerful enough to run it.
- New type of report that start appearing sometimes now (hard to pinpoint exactly when, but during this year), the user will play just fine for a couple of minutes, then the application will crash. Rence and repeat, they tell me they were able to play the game but they had to restart the game from time to time.

I have tried contacting some of these users to see if they could test some versions with different config running, sadly most users disappear and I wasn't able to have someone test anything yet. I'll see if I can find someone that has a phone crashing and is willing to test the issue in the future.

Maybe to try playing with these type of settings:
define config.image_cache_size = None
define config.hard_rollback_limit = 200
define config.image_cache_size_mb = 3000

And this one in particular:
define config.cache_surfaces 

See if it makes a difference... if someone has a phone that crash

**Comment by renpytom** [comment]
I'm not that familiar with Google Play myself, but thanks to everyone for reporting this. 

A 3,000 MB image cache size seems like it won't run on many devices - that's 3GB of video ram, so it's likely that we'll run out. That being said, there may also be a texture memory leak, so I'm going to look at that. 

I wouldn't expect cache_surfaces to do much, but then again, a bug is something that I don't expect, so it's good insight.

I'm going to run out to grab a low-end device that's been reported to have problems, so we'll see if I can reliably trigger things.

**Comment by Andykl** [comment]
We too have had problems with android 11. After a series of tests, I got these empirical data:
1. gl1 never crashes
2. gl2 not using advanced features does not crash
3. things like matrixtranform, matrixcolor or mesh=True (Flatten) cause crash
4. The crash happens not immediately, but after some time, because of Low Memory Killer Daemon.
5. As I understand it happens because of a memory leak in the texture code, because kill_textures and renders fixes the crash.
In the last release we added that function and a setting to enable it, and when it's enabled crashes don't happen.
```py
init python:
    def fix_android11(name):
        if renpy.is_init_phase():
            return

        cache = renpy.display.im.cache

        if fix_android11.statements_passed > 100:
            reason = "statements"

        elif cache.get_total_size() >= cache.cache_limit * 0.95:
            cache.clear()
            reason = "cache"

        else:
            fix_android11.statements_passed += 1
            return

        fix_android11.statements_passed = 0

        if renpy.game.interface is not None:
            renpy.game.interface.full_redraw = True
            renpy.game.interface.restart_interaction = True

            if renpy.display.draw is not None:
                renpy.display.draw.kill_textures()

            renpy.display.render.free_memory()

        renpy.write_log(
            "Textures cleanup, {}: {}".format(reason, renpy.get_filename_line()))
    fix_android11.statements_passed = 0
    config.statement_callbacks.append(fix_android11)
```
So, you can fix that issue by applying that function, or by `define config.gl2 = False` if you do not use gl2 features.

**Comment by Org-gith** [comment]
Just about the gl2 stuff, I had the issues happen on builds and none of them uses config.gl2 = True so I don't think it's enough to avoid the problem to have it disabled. Maybe it helps because it uses less ram but it shouldn't fully avoid the problem. 
The fix you made might be needed in all cases if that's the thing. 

Also, just an updated report, when I heard about the memory leak, it made sense to me and since my phone had 6GB ram, I realised it will take a lot of time for a problem like this to crash the application. This time, I stuck with it for a long time and I was able to have the issue replicated on my 'high-end' phone, it just took more time than on the usual reports because of all the ram available. This was with config.cache_surfaces = False.

Then I tested the version with define config.cache_surfaces = True, and redid the same step and it never crashed even after twice the time spent on it, doing the same exact thing, I have even reached the end of the game (whereas in the other run, I only got halfway), so I think it might have acted as a bandaid for the problem, maybe disabling the stuff that causes the memory leak or something like that.
Though I have noticed that config.cache_surfaces = False seems to make everything quite a bit slower overall (everything seem a bit more sluggish, and skipping is half speed almost), it would really just be a bandaid solution and far from ideal, I think.

**Comment by Andykl** [comment]
RenPy uses `gl2=True` by default since 7.4.5 (changed in 94031c2a691c8641f65c258813b73fbed06c66a9)

**Comment by Org-gith** [comment]
(ah sorry, I thought config.gl2 = False disabled it)

**Comment by renpytom** [comment]
Would it be possible for me to get the unpacked source for com.darkchibishadow.solanaceaeat ? I bought a Galaxy Tab A7 Lite, and ran it there, and it's now crashing reliably when I hit the start button. The crash is happening in glTexImage2D , and I'd like to rebuild the game with the current Ren'Py to see what's going on there.

**Comment by DarkChibiShadow** [comment]
> Would it be possible for me to get the unpacked source for com.darkchibishadow.solanaceaeat ? I bought a Galaxy Tab A7 Lite, and ran it there, and it's now crashing reliably when I hit the start button. The crash is happening in glTexImage2D , and I'd like to rebuild the game with the current Ren'Py to see what's going on there.
> 
> If you'd like to share it privately, please send it to [renpytom@gmail.com](mailto:renpytom@gmail.com).

Yes! I'll send it to you right now.

**Comment by renpytom** [comment]
I actually managed to repeat the crash with a version of solanaceaeat made from the PC version. The crash was interesting - it's a buserror with glTexSubImage2D, which shouldn't be possible - probably a bug in Android's OpenGL driver. I've fixed it, albeit only with the gl2 renderer.. 

I've also made a second set of changes to better deal with the Android lifecycle, which might affect the second issue at https://github.com/renpy/renpy/issues/3643#issuecomment-1152864890

I'd be very interested in any other crashes, especially the full stack traces that the Google Play console produces - if you have them, post them, and I can do my best to figure out what each corresponds to.  (No promises, but I'll do my best.)

**Comment by Org-gith** [comment]
Excellent, probably have to switch to GL2 for the android build in the future then, it seems like a must-have.
Just something, I was getting ready to do a bunch of android build running GL2 this time and see if I could replicate the other type of crash (the one that happens after 4-5 min of play), but when trying to install RAPT on the latest nightly build, it just doesn't seem to install it. It says the installation was successful, press proceeds to restart Ren'py, and after doing that it will ask again to install the RAPT as nothing happened (I also tried grabbing it from the repo and putting it in the folder manually, still the same problem.). 
Tried to do the same on the prerelease and on this one everything works, but I don't believe it has the fix(?).
For the google play console log, is there anything else that could also help? (the app is not on google play and far from ready for a launch, and I doubt they would validate that type of content anyway).

**Comment by mattmurdock0010** [comment]
I supoose the new nightly builds don't include the latest builds for android so I still have the error in version 7.5.x. The reason why I think, because the bug I reported earlier is still have in the nightly version(#3608 . I hope it will be updated soon.

**Comment by renpytom** [comment]
>image_cache_size_mb set to 1500mb

This seems kind of big, still, especially since it's not a precise number, due to overhead. I suspect there are still new phones out there with 2GB or less of RAM, and so filling up more than half of that with the image cache seems like a bad idea. (I'd suggest that maybe 300-500 MB would be the sweet spot.)

**Comment by Org-gith** [comment]
I have noticed the problem reported by mattmurdock0010, thought it was my phone but the keyboard confirm button to choose player name seems very irresponsible on Android, somehow was able to unlock it by smashing my face on it but yeah.

I think 3000mb was way too much and was very stupid of me. And I think I can definitely go down a bit more if anything, maybe with a conservative 1000mb of cache size. Let me explain my thoughts on this because what you said makes sense so I agree with it, but here is why I want to keep it a bit higher for this project specifically:
- Monitored the game's memory usage on PC and it peaks out at about 800mb. Want to squeeze out as much performance as possible on the devices capable of running it.
- I tested a lot of android phones for the game which I borrowed around, find out that almost any phone prior to 2017-2018 will be sluggish on it because of all the ATL and animation used. Just unplayable. Need a capable GPU to run it, all the phones that have a decent enough GPU to run it smoothly would have at least 3-4GB of memory.
- The statement above even if sometimes incorrect in some corner cases phone, is not a big deal to me. The game is supposed to release and be complete officially on Android in at least 5 more years, I'm counting on the technological progress of phones
to mitigate the issue by then.

**Comment by renpytom** [comment]
The latest nightly builds were having a problem installing DLC like rapt, but that should be fixed now. I checked, and text input is working fine on my devices.

**Comment by Org-gith** [comment]
It seems to work indeed, I have retested and I think I understand now what seems to be the issue with android input;

> persistent.playern = renpy.input("", default='', allow="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz", exclude=None, length=8, with_none=None, pixel_width=None)

The length argument is not being enforced correctly, I used to input a random name to get to the testing fast enough, and that name ended up trespassing the limit set (which shouldn't be possible) so it didn't let me press enter to validate the input. 
I have tested on PC and the character limit is correctly enforced on it, and I wouldn't be able to input more than the length argument says so I wouldn't be able to run into that issue.

**Comment by DarkChibiShadow** [comment]
I sadly still can't find any full crash reports via Google Play. The information seems to be very limited on my end, so I'm just gonna put in what I do have in case it helps.

![image](https://user-images.githubusercontent.com/77140159/174190749-54adc350-bee7-402f-96db-cdd266be2241.png)

![image](https://user-images.githubusercontent.com/77140159/174190812-4e0e2ec0-b55e-4b44-8ce0-3e356d814c4f.png)

![image](https://user-images.githubusercontent.com/77140159/174190857-636dc2f2-71ca-4ff4-8851-b1b4a2321354.png)

**Comment by npckc** [comment]
Hello, I wanted to comment on this issue since it still seems to persist in Ren'Py 8.1.1. A game I released recently has a 5.25% crash rate over a 30 day average, which is much higher than the Google Play reference value of 1.09%. Other games that have also been updated to Ren'Py 7.5/8.1 also have around the same crash rate. The more frequent crashing seemed to begin with 7.4/8.0 and updating to 7.5/8.1 does not see mto have helped.

With a higher crash rate, users leave bad reviews and Google Play also shows the game less in searches.

**Comment by renpytom** [comment]
I could use more information like what DarkChibiShadow mentioned above. Unfortunately, without knowing what devices the games are failing on, and the information google gives you, it's hard to do anything to diagnose the problem. 

Is the quit button (and similar ways of quitting) disabled in your android port?

**Comment by npckc** [comment]
The quit button is disabled, but I will be adding it in a future update at Google's request for use only on the main menu of the game. 

Here are some screenshots as well as the stack trace for the most frequent crash. 

![screenshot_1](https://github.com/renpy/renpy/assets/50103058/386cb25a-68cd-4909-a103-fe5de1635684)
![screenshot_2](https://github.com/renpy/renpy/assets/50103058/db1c33b6-67f2-4d07-8fd9-1e78260facb5)
[stacktrace.txt](https://github.com/renpy/renpy/files/13507659/stacktrace.txt)

If there is other information that would be helpful please let me know.

**Comment by renpytom** [comment]
I have an idea of what could be causing the crash in libGLESv2_mtk.so. Could you pull a few more of these stack traces for me?

**Comment by npckc** [comment]
Here are some more stack traces over various devices. If there is any one specific crash device you would like to have more stack traces from, I can pull more.

[samsung gta7litewifi (Galaxy Tab A7 Lite) Android 13 (SDK 33).txt](https://github.com/renpy/renpy/files/13532806/samsung.gta7litewifi.Galaxy.Tab.A7.Lite.Android.13.SDK.33.txt)
[google hana_cheats (Mediatek MT8173 Chromebook) Android 9 (SDK 28).txt](https://github.com/renpy/renpy/files/13532807/google.hana_cheats.Mediatek.MT8173.Chromebook.Android.9.SDK.28.txt)
[ZTE P963F07 (ZTE A7030) Android 11 (SDK 30).txt](https://github.com/renpy/renpy/files/13532808/ZTE.P963F07.ZTE.A7030.Android.11.SDK.30.txt)
[Redmi water (Redmi A2+) Android 13 (SDK 33).txt](https://github.com/renpy/renpy/files/13532809/Redmi.water.Redmi.A2%2B.Android.13.SDK.33.txt)
[Vortex HD65 (HD65) Android 13 (SDK 33).txt](https://github.com/renpy/renpy/files/13532810/Vortex.HD65.HD65.Android.13.SDK.33.txt)
[samsung a10s (Galaxy A10s) Android 11 (SDK 30).txt](https://github.com/renpy/renpy/files/13532811/samsung.a10s.Galaxy.A10s.Android.11.SDK.30.txt)
[samsung a03s (Galaxy A03s) Android 13 (SDK 33).txt](https://github.com/renpy/renpy/files/13532812/samsung.a03s.Galaxy.A03s.Android.13.SDK.33.txt)
[samsung a3core (Galaxy A03 Core) Android 11 (SDK 30).txt](https://github.com/renpy/renpy/files/13532813/samsung.a3core.Galaxy.A03.Core.Android.11.SDK.30.txt)

**Comment by renpytom** [comment]
I'm tracking these stack traces in #5152, since the traces seem to come from the same thing. (A bug in the mediatek opengl es2 driver.) 

@npckc , can you join me there?

**Comment by Andykl** [comment]
Since Ren'Py 8.3 I don't see Android crashe reports in volumes in was at the time, so I think this issue is resolved, and anything new would be regression or new issue.
