### ISSUE TITLE
Constant renpy crashes on android 11

### ISSUE THREAD

**Issue by Calzos** [renpy/renpy#3754]
After installing Android 11 I can no longer play any visual novels they just seem to always crash about 5 minutes or so after starting them, I didn't have this issue when I was on Android 10 and I can't downgrade because Samsung locks their devices. Anyone else experience this? It's beyond frustrating.

**Comment by renpytom** [comment]
Are these games made with Ren'Py 8.0 or 7.5? There is a fix there for a bug in Samsung's OpenGL ES implementation.

**Comment by JVMJohnny** [comment]
> Are these games made with Ren'Py 8.0 or 7.5? There is a fix there for a bug in Samsung's OpenGL ES implementation.

I'm having the same problem since i've updated, is there a way for me to update de Ren'Py versio, of the game even not being the developer? Or another way to fix it?

**Comment by JVMJohnny** [comment]
> After installing Android 11 I can no longer play any visual novels they just seem to always crash about 5 minutes or so after starting them, I didn't have this issue when I was on Android 10 and I can't downgrade because Samsung locks their devices. Anyone else experience this? It's beyond frustrating.

Have you solved it?

**Comment by renpytom** [comment]
This is likely fixed in Ren'Py 8.0 and 7.5.

**Comment by Calzos** [comment]
> > After installing Android 11 I can no longer play any visual novels they just seem to always crash about 5 minutes or so after starting them, I didn't have this issue when I was on Android 10 and I can't downgrade because Samsung locks their devices. Anyone else experience this? It's beyond frustrating.
> 
> Have you solved it?

I haven't solved this, I've literally tried everything. I just decided to give up trying to run visual novels on my phone.

**Comment by Calzos** [comment]
> This is likely fixed in Ren'Py 8.0 and 7.5.

Can confirm that is not fixed, Still crashes in under 5 minutes every time when trying to play any visual novel. 

Novels that haven't been updated since 2021 seem to work without any crashes but any in that have been updated in 2022 crash constantly.

**Comment by Andykl** [comment]
Could you check in game's about screen if it's RenPy 7.5? It's likely developers updated the game but not version of RenPy they use. We also had issues with Android 11 especially on Samsung but it was fixed within RenPy.

**Comment by Calzos** [comment]
> Could you check in game's about screen if it's RenPy 7.5? It's likely developers updated the game but not version of RenPy they use. We also had issues with Android 11 especially on Samsung but it was fixed within RenPy. In case they have not updated RenPy you could contact developers with the link to this issue.

Hi it seems that you're probably right, Not all visual novels have an about section so it's hard to tell what a lot of them are running on but the majority of the one's I have recently tested have new game update releases but are still running on older versions of RenPy specifically 7.4.10 and 7.3.5.

**Comment by JonIzanagi** [comment]
i'm experiencing the same, I can no longer play any visual novels they just seem to always crash about 5 minutes or whenever i start saving/loading.

**Comment by hubertgrzeskowiak** [comment]
I tried RenPy in latest version 7 and 8. Both eventually (after some fights with JDK versions) produced an Android APK, which starts on my phone, but each crashes right after the loading screen.
