### ISSUE TITLE
Error at creating new project in several languages

### ISSUE THREAD

**Issue by giancarlozero** [renpy/renpy#4710]
Hello!

I encountered a bug while creating a new game project in **Ren'Py version 8.1.0.23051307** in the Portuguese language. The project was created with errors and missing files and the launcher displayed the error message shown in the following image.

![renpy-error-portuguese-portugues](https://github.com/renpy/renpy/assets/166841/04c675cd-102e-4e8b-bccd-9a1bdfe78901)

I tested creating projects in all other languages and noticed that the problem was ocurred in the following languages:

- Portuguese/Português
- Bahasa Indonésia
- Deutsch/Alemão
- Polski/Polonês
- Suomi/Finlandês
- Korean/Coreano

### More screenshots:

![renpy-error-deutsch-alemao](https://github.com/renpy/renpy/assets/166841/8d86aeed-5877-449b-bcfd-cedb0432f5f0)
![renpy-error-piglatin](https://github.com/renpy/renpy/assets/166841/f8f89468-34e0-4092-b7e8-ec76a7c03806)
![renpy-error-polski-polones](https://github.com/renpy/renpy/assets/166841/a65d9c97-7290-4dcb-bc72-e1effc12f2f9)
![renpy-error-bahasa-indonesia](https://github.com/renpy/renpy/assets/166841/ba39ae7c-49d5-4f3b-9dec-de7c7013adc9)

### Steps to reproduce the error:

1 - Open the Ren'Py launcher;
2 - Choose one of the languages listed above;
3 - Click on the "+ Create New Project" button;
4 - Name the new project (without accents);
5 - Advance through the screens. The bug occurs after the color palette selection screen.

When trying to create a project in the Pig Latin language, a different error occurred than in the other languages I mentioned.

I hope you can resolve this bug. I'll be glad to help with further testing if needed.

(Sorry about my bad english. Using Google Translate)

**Comment by Gouvernathor** [comment]
Test this again using today's Release, it should be fixed now (since several nightlies really).

**Comment by giancarlozero** [comment]
Tested now in this new release (version 8.1.1.23060707). The bug is still ocurring in two languages: Polski and PigLatin.

Here more screenshots:

Polski
![renpy-newerror-polski](https://github.com/renpy/renpy/assets/166841/c3ba17d5-931d-436e-a05a-f81a82e2bafa)

PigLatin
![renpy-newerror-piglatin](https://github.com/renpy/renpy/assets/166841/766057f5-300e-4b3e-953d-48e11c5f9044)

**Comment by Gouvernathor** [comment]
The Polish part is fixed by c2c094f, the Piglatin fix is in progress. Thanks for the testing and report.
