### ISSUE TITLE
Very poor software video playback performance on Windows

### ISSUE THREAD

**Issue by RadarNyan** [renpy/renpy#4817]
There were some closed issues related to video playback performance, but I'm still experiencing serious performance problems with the latest versions (both 7.6 and 8.1 branches).

The CPU usage is very high, and the video doesn't play smoothly at all. When I try to play the same video file with MPC-BE + LAV Filters it plays smoothly with no frames dropped and reasonable CPU usage.

If I understand correctly, Ren'Py uses FFmpeg for video playback, which is what LAV Filters is based on as well. Why is the performance difference so great?

(I wrote Windows in the title because it's the only platform I've tested on. The sample video provided in now-closed issue #4070 doesn't play nice for me either, so I don't think my video files are the cause.)

**Comment by renpytom** [comment]
Do you have an example of a movie file that is having problems? Ren'Py's movie playback is optimize for some formats, and not others - specifically, yuv420 is fast, and yuv444 is very slow.

**Comment by RadarNyan** [comment]
It turns out the GPU in my machine is too old (well, kinda hard to get a new GPU in recent years) to support hardware decoding of VP9, and the software decoding performance of Ren'Py is just very, very bad.

I can watch 1080P YouTube (VP9) videos just fine, and if I push the limit, the CPU can do software VP9 playback (using LAV filters) of 2560x1440 ~48fps (at ~20% CPU usage). However, when I try to play the same video file in Ren'Py despite very high CPU usage (reaching 100%), the playback experience is terrible (like no more than 10 fps to my eyes). Even if I lower the resolution of the video down to 1080p, Ren'Py still struggles to play it smoothly.

I understand that for legal reasons, Ren'Py couldn't include H.264 support (which is a shame since almost any device that somewhat works today supports hardware decoding of that). WebM's royalty-free nature seems to be a good choice, but with this kind of software decoding performance, it's unusable for my (old) machine. It would be nice if the software decoding performance could be improved to be on par with others, or maybe include platform-specific workarounds to do video playback natively, like using DirectShow Filters on Windows? Even without stepping into the gray area of using H.264, at least that would provide decent software decoding performance for VP9.

**Comment by renpytom** [comment]
Ren'Py doesn't use hardware decoding, in any case - it's a visual novel engine, not a media player. My feeling is that there's likely something wrong here. Have you checked if your file is using yuv444p? That's slow to turn to into RGB.

**Comment by RadarNyan** [comment]
> Ren'Py doesn't use hardware decoding, in any case - it's a visual novel engine, not a media player. My feeling is that there's likely something wrong here. Have you checked if your file is using yuv444p? That's slow to turn to into RGB.

So you mean even if I have a GPU that is capable of hardware decoding of VP9, Ren'Py would still do software decoding nonetheless? I mean... it doesn't really make sense that visual novels need a very powerful CPU just to play some video clips, right? It might be okay for a desktop, but on the mobile side, this sounds like a very bad idea.

I've tried clips in both yuv420p and yuv444p. One of the clips is 1080p60fps [V: vp9 profile 0, yuv420p, 1920x1080], when playing this clip with MPC-BE using LAV filters, the playback is smooth (I can see it rarely dips below 60 fps with OSD info) with reasonable CPU usage, but when playing the same clip in Ren'Py the CPU usage is nearly 100%, yet the playback is very choppy and unpleasant to watch - I'd say barely 10 fps to my eyes.

Since they're both doing software decoding based on FFmpeg, why is the performance in Ren'Py so bad compared to LAV filters?

**Comment by lavilao** [comment]
@RadarNyan according to documentation hw decoding is supported in mobile. ```On mobile platforms, such as Android and iOS, hardware video decoding is used when [config.hw_video](https://www.renpy.org/doc/html/config.html#var-config.hw_video) is changed to True. This can be faster, but the list of supported movie formats depends on the platform.```

**Comment by renpytom** [comment]
> So you mean even if I have a GPU that is capable of hardware decoding of VP9, Ren'Py would still do software decoding nonetheless? 

That's correct. It's the rare computer that can't decode at 1x, nowadays. What sort of computer do you have?

Ren'Py isn't a movie player, and the goal is to have something that just works, not something that works if you have external drivers installed and not. I understand your'e having problems. At this point, I'd like you to put together a small demo so I can see what's going on (assuming your computer is reasonably modern).

>  hw decoding is supported in mobile

This used to be the case, but it will likely be going away soon, as it hasn't been the preferred path for years.

**Comment by lavilao** [comment]
> This used to be the case, but it will likely be going away soon, as it hasn't been the preferred path for years.

thats going to be a shame as in mobile the reason for amazing battery life and good performance even in low end devices is the use of hw decoding (not just in renpy but for everything in general). But thank you nonetheless for making this amazing engine. On the desktop side I also suffer from poor video playback performance as @RadarNyan  I have a pretty trash laptop with an intel celeron n3050 and 4gb of ram, the funny thing is that its not always the case because there are games that will playback really slow yet there are others that work flawlessly. I always use the compressed versions of the games I play.

**Comment by RadarNyan** [comment]
I have a desktop PC with an Intel i7 processor and a laptop with an ultra-low-voltage Intel i5 processor (15W TDP). I know my specs aren't by any means recent, but they still work fine. They can play 1080P YouTube videos (VP9) without hardware acceleration just fine.

For the same 1080p60fps video clip (vp9 profile 0, yuv420p), playing with MPC-BE using LAV filters on both machines results in a smooth experience with no frames dropped. CPU usage on the desktop (with hardware decoding disabled) is around 20%, while it is 60% on the laptop. But when trying to play the same clip in Ren'Py (I'm not doing anything fancy, just following the documentation to use it as a Movie Sprite), only the desktop can handle it with no frame drops, but CPU usage shoots up to over 60%, and on the laptop, playback is very, very choppy with CPU usage frequently reaching 100%.

I understand that hardware decoding is very platform-dependent and software decoding provides the best compatibility, but this kind of performance is just horrible. When I mentioned mobile devices previously, I was referring to devices with limited power, smartphones, laptops, and those new x86 handhelds. Even if it managed to play the video with high enough raw horsepower, there are still problems with heating and battery drain as lavilao has mentioned.

**The problem is: Ren'Py has very terrible software decoding performance on the same hardware, with 3 times the CPU usage (based on my very limited tests) compared to LAV filters which is also based on FFmpeg.** Yes, a powerful enough CPU can handle it, but that's not really a preferred solution for a visual novel engine. I don't think it's reasonable for a 2D visual novel game to have a very high hardware requirement for CPU speed, this kind of game should be the most accessible for low-end devices.

**Comment by lavilao** [comment]
Could it be the decoder? On mpv on intel gpus if you use vd-lavc-dr=yes to play non hw accelerated videos the playback will be really bad yet if you use vd-lavc-dr=no or the libvpx-vp9 decoder (wich uses the  naive upload frame method by default instead of DR) then the playback is fine. Could it be that renpy uses DR when playing with ffmpeg?

**Comment by RadarNyan** [comment]
> Could it be the decoder? On mpv on intel gpus if you use vd-lavc-dr=yes to play non hw accelerated videos the playback will be really bad yet if you use vd-lavc-dr=no or the libvpx-vp9 decoder (wich uses the naive upload frame method by default instead of DR) then the playback is fine. Could it be that renpy uses DR when playing with ffmpeg? this is an intel gpu specific bug. edit: Also, this bug is only present with opengl, if you use vulkan or directx it will be fine.

I forgot to mention that my desktop doesn't have an Intel GPU (the integrated graphic is disabled on the motherboard, doesn't even show up in Windows Device Manager), and I have an Nvidia card that is capable of hardware VP9 decoding, and surely Ren'Py doesn't utilize that (hence the very high CPU usage).

So if this bug you mentioned is Intel-specific, that shouldn't be the case here, as I'm observing the same behavior with an Nvidia card.

**Comment by lavilao** [comment]
> > Could it be the decoder? On mpv on intel gpus if you use vd-lavc-dr=yes to play non hw accelerated videos the playback will be really bad yet if you use vd-lavc-dr=no or the libvpx-vp9 decoder (wich uses the naive upload frame method by default instead of DR) then the playback is fine. Could it be that renpy uses DR when playing with ffmpeg? this is an intel gpu specific bug. edit: Also, this bug is only present with opengl, if you use vulkan or directx it will be fine.
> 
> I forgot to mention that my desktop doesn't have an Intel GPU (the integrated graphic is disabled on the motherboard, doesn't even show up in Windows Device Manager), and I have an Nvidia card that is capable of hardware VP9 decoding, and surely Ren'Py doesn't utilize that (hence the very high CPU usage).
> 
> So if this bug you mentioned is Intel-specific, that shouldn't be the case here, as I'm observing the same behavior with an Nvidia card.

I dont know what could be then. Have you tried to use an alternative renderer? Most newer games should already use them but if not you can try the gl2 (or angle2) renderer by pressing shift+g, choosing the renderer and restarting the game. See if it improves

**Comment by renpytom** [comment]
I think the issue here is that we have a 9 year old 2-core processor that was underpowered when it was released, and it can't keep up with decoding video in modern formats. I don't think there's much I can do to that - my sense is that this computer is just too slow to do what you want. 

Patches that address this issue are welcome, though my feeling is that moving to hardware video decode is more trouble than it's worth. 

Until then, I'm going to close this.

**Comment by renpytom** [comment]
Oh, sorry, confused the two computers in play. RadarNyan, what processor do you have? I'd like to figure out if it should be able to decode video.

**Comment by RadarNyan** [comment]
I deliberately didn't mention the exact processor name because it doesn't really mean much and could lead to misjudgment. A newer CPU doesn't necessarily provide better raw performance, and different laptops would perform differently depending on the RAM speed and cooling capability. 

What matters is the fact that I can watch YouTube videos at 1080p30fps with Chromium browser (no frame drops, reasonable CPU usage), suggesting the machine is capable of somewhat high-quality VP9 video software decoding.

Even with a powerful desktop CPU, I can still observe that (for the same VP9 video clip) Ren'Py uses significantly more CPU compared to FFmpeg-based LAV Filters (hardware decoding disabled). Since Ren'Py is also using FFmpeg to do video decoding, why is the performance so much worse? The hardware is clearly capable of doing the job, as proved by both Chromium and LAV Filters, it's only Ren'Py that struggles while doing the same task.

**Comment by renpytom** [comment]
I'm trying to figure out if your laptop is in the range of computers that I'd like to support. That's generally machines that were sold in the past 6-8 years, depending on the specs of the machine. If the computer is something that should be supported, then I can look into it. But "computer is too slow" is a perfectly valid disposition, which is why I'm trying to determine if that is the case.

I don't think it's absurd that Ren'Py uses 2x CPU compared to chrome, no. I'm closing this issue now, and if you'd like to provide the information I've requested, please re-open the issue.

**Comment by summerlight** [comment]
This looks interesting. I confirmed that 7.5.0 is the first release that has this problem while 7.4.11 can decode/render a yuv444/gbrp video in a real time. All the nightly releases between them have gone a long time ago so I cannot further bisect. I also noticed that 7.5.0 generally takes more a CPU time than 7.4.11 even for yuv420p. ffplay in my computer can decode yuv444p/gbrp videos in a real time (though those formats took more a bit more CPU time), so I guess there might be another contributor.

One more interesting observation is that I could not reproduce this problem in the development environment (following the process in README), so I guess some build/dependency side changes could be culprits? I tried to profile it but without reproducing the performance issue it's hard to proceed.

**Comment by KiaArmani** [comment]
Using RenPy 8.1.2 I am also running into issues with video playback. I have a 4k webm file (VP9) that runs extremely slow in desktop mode (browser seems fine). GPU at 30% usage, with spikes up to 100%. 

I have a 16-core CPU and a RTX 4090, so the hardware should be more than capable of running this.

ffprobe output:

```
Input #0, matroska,webm, from '.\Intro_Shot1.webm':
  Metadata:
    encoder         : libwebm-0.3.0.0
    creation_time   : 2023-09-16T14:40:10.000000Z
  Duration: 00:00:20.03, start: 0.000000, bitrate: 2509 kb/s
  Stream #0:0(eng): Video: vp9 (Profile 0), yuv420p(tv), 3840x2160, SAR 1:1 DAR 16:9, 30 fps, 30 tbr, 1k tbn (default)
```

Use in script
```
image intro_shot1 movie = Movie(play="movie/Intro_Shot1.webm")
```

**Comment by AugustEsoterica** [comment]
> This looks interesting. I confirmed that 7.5.0 is the first release that has this problem while 7.4.11 can decode/render a yuv444/gbrp video in a real time. All the nightly releases between them have gone a long time ago so I cannot further bisect. I also noticed that 7.5.0 generally takes a more CPU time than 7.4.11 even for yuv420p. ffplay in my computer can decode yuv444p/gbrp videos in a real time (though those formats took more a bit more CPU time), so I guess there might be another contributor.
> 
> One more interesting observation is that I could not reproduce this problem in the development environment (following the process in README), so I guess some build/dependency side changes could be culprits? I tried to profile it but without reproducing the performance issue it's hard to proceed.

Echoing this. The difference in 4k video playback between 7.4.11 and 8.1.2 is night and day, even at yuv420. I've been going crazy trying to figure out how to encode playable video, and running the game in 7.4.11 is the only solution that's completely eliminated the stuttering. 

Even at disgustingly low bitrates and resolutions, video in 8.1.2 has a tendency to lag/stutter for the first second or so, and certainly comes nowhere close to 60fps smooth. 7.4.11 doesn't seem to have this problem at all, even allowing 4k videos to play back to back with no problem at a buttery smooth 60fps.

**Comment by renpytom** [comment]
Have you tried the nightlies? There has been a fix (mmx support is actually enabled in the nightlies).

**Comment by summerlight** [comment]
Looks like this is fixed with the latest nightly (I tried `8.1.3.23091403+nightly`). Thank you!

**Comment by AugustEsoterica** [comment]
> Have you tried the nightlies? There has been a fix (mmx support is actually enabled in the nightlies).

I was under the impression that was implemented back in 8.1.2? 

Regardless, seems like the issue persists in
 8.1.3.23091403+nightly 
and 
8.2.0.23091603+nightly, at least for me.

**Comment by summerlight** [comment]
FYI, I'm using Windows on x64 ([mmx is disabled on some other platforms](https://github.com/renpy/renpy-build/blob/77d370ba11ef1f6db3f99c8214132be78391e7f3/tasks/ffmpeg.py#L99-L102)).

**Comment by AugustEsoterica** [comment]
I'm on Windows 11 x64. I took some video of the problem.

NSFW Warning 
(Brief 3D adult man ass. Sorry, it's the best comparison I have atm)

8.1.3.23091403+nightly
https://mega.nz/file/LuRzRQ6S#eDAhcTX_u-GOcHIZTylTYa_kpF0UqSxH_GKFQfHEtqY

7.4.11
https://mega.nz/file/DzpFVR4Y#FCqt0cL1G-qE4nkvdQT8OEpbjd7QdBuTwas77aOZpME

The startup stuttering seems to have been reduced somewhat on 8.1.3, but it should be clear there's still some kind of problem with the playback. Sees almost like it's capped at 30 FPS. (It's not, I checked.)

Captured and downscaled to 1920x1080 with OBS (Ren'py playback was in 4k.)

**Comment by KiaArmani** [comment]
Can confirm that with renpy-8.1.3.23091403+nightly-sdk video playback is working as intended.

**Comment by FinderX** [comment]
Providing my 2 cents.  I use linux for renpy games.  Same problem as the original post.

2 games with renpy 8.0.X version.
Both were throwing me a CPU bottleneck at 100% when playing videos.
The videos were stuttering and sometimes my PC crashed.

To solve the problem momentarily, I had to download the latest version of the SDK 8.1.3.X and ran the game using the command explained in the renpy documentation:

[64-Bit Linux Problems](https://www.renpy.org/doc/html/problems.html#bit-linux-problems)
`/path/to/renpy-8.1.3.X/renpy.sh /path/to/game-with-problems`

And now the games go from 100% to 50% CPU in one game and from 100% to ~70% in another, both videos are smooth without any problems.

**Comment by lavilao** [comment]
Can confirm, using the latest stable sdk to run the game fixes the video playback on my potato

**Comment by SempakRangerGG** [comment]
Everyone seem to blame other people computer like "its just too slow and renpy is not video player" when they could play the videos using even basic video player outside. So defensive without actually helping. Especially the guy like renpytom

**Comment by izarii-dev** [comment]
> Everyone seem to blame other people computer like "its just too slow and renpy is not video player" when they could play the videos using even basic video player outside. So defensive without actually helping. Especially the guy like renpytom

Ren'Py now does [YUV to RGB conversion using shader](https://github.com/renpy/renpy/pull/7228), so the situation should be much better now
