### ISSUE TITLE
Error when building Renpy

### ISSUE THREAD

**Issue by Gouvernathor** [renpy/renpy#4882]
![image](https://github.com/renpy/renpy/assets/44340603/081dcddc-9e2c-4ac8-a538-e95aabd11cac)

**Comment by renpytom** [comment]
Fixed by renpy/renpy-build@8bbb3e5

**Comment by Gouvernathor** [comment]
Still unable to build
There is a lot of  the same error over and over in different files (I think it's because hb.hh is imported in a lot of files).
![image](https://github.com/renpy/renpy/assets/44340603/b227ae12-2204-4a22-a96b-47047c9ea76e)

**Comment by renpytom** [comment]
Have you tried starting over with a clean checkout, and running prepare.sh again? I did just rebuild from scratch in a new VM, and it worked.

**Comment by renpytom** [comment]
This is fixed, right?

**Comment by Gouvernathor** [comment]
yep
