### ISSUE TITLE
Linux: Trailing slash at the end of projects.txt directory path causes project name to be blank

### ISSUE THREAD

**Issue by hsandt** [renpy/renpy#5087]
Tested platform: Linux Ubuntu 20.04

Repro:

1. Create a new project and move it outside the main project directory
2. Add global path to this project directory in renpy-sdk/projects.txt => project appears properly
3. Add a trailing slash at the end of the directory path => project name appears blank

![image](https://github.com/renpy/renpy/assets/1067772/a86618db-2301-42c7-9948-a2a8c9f2b996)

In the screenshot above, look at the blank space highlighted in orange: this is my external project, with a blank name. Other functionality, such as playing the game, works fine, only the name is blank and as a side effect it causes it to be at the top since projects are sorted alphabetically.

This could be fixed by ignoring the trailing slash in the path.

Alternatively, you could support trailing slash to mean "this is a parent folder, scan it recursively" (which would also be a great feature, when reading the [doc](https://www.renpy.org/dev-doc/html/launcher.html) for the first time I thought it was recursive), but then you'd have to be careful when implementing https://github.com/renpy/renpy/issues/3668 as some of our suggestions rely on the fact we add specific projects to the list, rather than parent folders.

In the meantime, we could also update the [doc](https://www.renpy.org/dev-doc/html/launcher.html) to indicate dev must enter exact project path, without trailing slash.

**Comment by Gouvernathor** [comment]
It says "These paths are treated **as if they were inside the projects directory**", not "These paths are treated as additional project directories", so for me it's work as intended (though it can always be phrased more clearly).
I take the bug as-is, but I don't think a trailing slash should change the behavior, that's just not how path are supposed to work in my view. But we could start supporting trailing stars like \* or \*\* to mean that.

**Comment by renpytom** [comment]
This should be fixed already.  Have you tried it with a nightly?

**Comment by hsandt** [comment]
> This should be fixed already. Have you tried it with a nightly?

Excellent, it was fixed somewhere between 8.1.2.23071001 and 8.1.4.23110301!

Then you can ignore my other suggestions. I also prefer that trailing slash has the same meaning as no trailing slash when you expect a directory.

**Comment by hsandt** [comment]
Ah... I just found out that on Windows, a trailing backslash `\` (in fact, any number >= 1 of backslashes) still show the empty project name error. I should have thought about that and asked you to verify backslash at the same time, but I wasn't on Windows at that time to verify my hypothesis.

I'll open another bug...

P.S.: Amusingly though, a forward slash **will** work on Windows, although it's not really used (`C:\path\to\project/`)
