### ISSUE TITLE
fullscreen bug on web?

### ISSUE THREAD

**Issue by Neyunse** [renpy/renpy#5140]
I have two projects created for web, and I have a strange bug. When I put the game in full screen and return it to "windowed" mode, the canvas becomes a smaller size. However, it happens with some games.

![image](https://github.com/renpy/renpy/assets/36079551/51bfa7f5-a49a-4f2f-ac6b-0b450c4e3d81)

[log (1).txt](https://github.com/renpy/renpy/files/13430175/log.1.txt)

![image](https://github.com/renpy/renpy/assets/36079551/da268f54-4566-4807-9287-2c1b70c62864)

[log (2).txt](https://github.com/renpy/renpy/files/13430182/log.2.txt)

another thing i noticed is that testing it from renpy launcher, the window moves to the side when resizing.

**Comment by Kassy2048** [comment]
For the web behavior, it looks like an issue that have been fixed previously, so please try with a nightly build if that's not your case already. Otherwise, please indicate on which web browsers you see that.

**Comment by Neyunse** [comment]
> For the web behavior, it looks like an issue that have been fixed previously, so please try with a nightly build if that's not your case already. Otherwise, please indicate on which web browsers you see that.

Do you have any idea what commit this patch was added to? 

Opera: 105.0.4970.16
OS: Linux Mint 21.2 Cinnamon
Ver: 5.8.4

**Comment by Neyunse** [comment]
Update: 8.1.4.23112006+nightly

The problem remains, it seems that when using F11 it does not give problems, but it seems that the problem is in:

* action Preference("display", "fullscreen")
* action Preference("display", "window")

**Comment by Kassy2048** [comment]
[This PR](https://github.com/renpy/renpy-build/pull/77) should have fixed it.

I can't reproduce that behavior using The Question using Chrome, Firefox, Edge or Opera on Windows. Maybe this only happens on Linux or Mint? I'll check on Ubuntu later.

**Comment by Neyunse** [comment]
> [This PR](https://github.com/renpy/renpy-build/pull/77) should have fixed it.
> 
> I can't reproduce that behavior using The Question using Chrome, Firefox, Edge or Opera on Windows. Maybe this only happens on Linux or Mint? I'll check on Ubuntu later.

RP: 8.1.3 (initial test)

![image](https://github.com/renpy/renpy/assets/36079551/c35b3500-791c-4d8c-903d-2c4ef9cc5686)


RP: 8.2.0.23112302+nightly

Opera (action)

![image](https://github.com/renpy/renpy/assets/36079551/1e03ef01-d711-48a9-802b-0137c1fcb515)

Firefox (F11 and action)
![image](https://github.com/renpy/renpy/assets/36079551/32ff9a78-545c-43f5-a00f-4bfceaa3c276)


Chrome (F11 and action)
![image](https://github.com/renpy/renpy/assets/36079551/7f4e0847-8320-4801-9cf0-d93799cc29f3)

RP: 8.1.4.23112006+nightly

Opera (action)

![image](https://github.com/renpy/renpy/assets/36079551/1e03ef01-d711-48a9-802b-0137c1fcb515)

Firefox (F11 and action)
![image](https://github.com/renpy/renpy/assets/36079551/32ff9a78-545c-43f5-a00f-4bfceaa3c276)


Chrome (F11 and action)
![image](https://github.com/renpy/renpy/assets/36079551/7f4e0847-8320-4801-9cf0-d93799cc29f3)


OS: Windows 11

**Comment by bober-gith** [comment]
I remember this problem, it existed on ren'py web 7 too. 

The "fix" was to call Preference("display", "window") a second time, after using Preference("display", "window").
Here is an example to test if it's the same issue:

```
                    vbox:
                        style_prefix "radio"
                        label _("Display")
                        textbutton _("Window") action Preference("display", "window"), Show('noclick_web_fix")
                        textbutton _("Fullscreen") action Preference("display", "fullscreen")
```

```

screen noclick_web_fix():
    layer "menu"
    zorder 999999999999999999999999999999999
    modal True

    key "K_m" action Preference("display", "window"), Hide("noclick_web_fix")
    if not open_dropdown_resolution and not open_dropdown_settingskip:
        key "mouseup_3" action Preference("display", "window"), Hide("noclick_web_fix")
    key "K_ESCAPE" action Preference("display", "window"), Hide("noclick_web_fix")
    button:
        xpos 0
        ypos 0
        xysize (1920, 1080)
        action Preference("display", "window"), Hide("noclick_web_fix")

```

That makes it that after you set the game to windowed (when you are in fullscreen), if you press any key, it should fix the window of the game.

(Not advocating for this bad fix, but if it helps identify the core problem, potentially useful.)

**Comment by Kassy2048** [comment]
@Neyunse Do you have the same behavior with the game "The Question" which is shipped with Ren'Py?

@bober-gith The goal of #4782 was to fix this so these changes are probably not needed anymore.

**Comment by Neyunse** [comment]
> @Neyunse Do you have the same behavior with the game "The Question" which is shipped with Ren'Py?
> 
> @bober-gith The goal of #4782 was to fix this so these changes are probably not needed anymore.

No, work correctly. And that is the strange thing, since an empty project does not give problems but an already worked project does. The issue is that the project has nothing, it has dialogs, it is not modified in its totality.

I guess the problem must be in gui.init

**Comment by Neyunse** [comment]
maybe, web not support 1080p

**Comment by Kassy2048** [comment]
Your game seems to behave as if the "web" variant has been replaced with "pc" so maybe check you don't have some code that does that (which would be weird). Or at least, check at runtime that the "web" variant is set when your game is built for the Web platform.

When new Ren'Py versions are released, there can be some changes to the "options.rpy", "screens.rpy" and "gui.rpy" files, but they don't get applied to games that have been created with previous versions, so that might explain why new games don't show this issue but old do. So check the changes to these files between your game and a blank new game created with the last Ren'Py version.

The display size does not really matter for the web platform.

If you still can't find the problem, you may contact me on discord (Kassy2048 on Ren'Py's server) so I can have a look at your project files.

**Comment by Neyunse** [comment]
> Your game seems to behave as if the "web" variant has been replaced with "pc" so maybe check you don't have some code that does that (which would be weird). Or at least, check at runtime that the "web" variant is set when your game is built for the Web platform.
> 
> When new Ren'Py versions are released, there can be some changes to the "options.rpy", "screens.rpy" and "gui.rpy" files, but they don't get applied to games that have been created with previous versions, so that might explain why new games don't show this issue but old do. So check the changes to these files between your game and a blank new game created with the last Ren'Py version.
> 
> The display size does not really matter for the web platform.
> 
> If you still can't find the problem, you may contact me on discord (Kassy2048 on Ren'Py's server) so I can have a look at your project files.

i only see changes on "screens.rpy", probably was internal changes

**Comment by renpytom** [comment]
I rewrote the way web goes fullscreen tonight - bypassing emscripten's behavior to make the html element fullscreen. This should fix a lot of problems - once the 20240101 build of 8.2 is out, please check to see how it's working.

**Comment by Neyunse** [comment]
> I rewrote the way web goes fullscreen tonight - bypassing emscripten's behavior to make the html element fullscreen. This should fix a lot of problems - once the 20240101 build of 8.2 is out, please check to see how it's working.

Fixed
