### ISSUE TITLE
Last retained frame disappears.

### ISSUE THREAD

**Issue by renpytom** [renpy/renpy#5564]
@lokanathshankar in #4732 

> Hi, Just a quick observation. When you use keep_last_frame and let the clip/movie play to the end, advance couple of images or interactions and then upon rollback the last frame from the video is not getting retained. I hope this isn't a intended feature, atleast from the player perspective we have to treat the last frame as an displayable and load it back upon rollback is what I feel.
> This observation is with Renpy 8.2.1.24030407.
> PS : oh btw this is an amazing enhancement.

**Comment by renpytom** [comment]
@lokanathshankar I'm unable to repeat this in Ren'Py 8.3. 

My test was:

```renpy

label start:

    scene
    show expression Movie(play="oa4_launch.webm", loop=False, keep_last_frame=True)

    "A"

    "B"

    "C"

    "D"

    return
```

Then allowing the movie to end, clicking forward, and rollback back. oa4_launch.webm can be found in the tutorial game. 

My guess is that this was fixed along the way, so I'm closing it. Feel free to re-open if you can repeat the problem.

**Comment by the66F95** [comment]
@renpytom there is still an issue when rolling back after a movie was shown, and it doesn't matter if it's looped or not or the last frame is kept.

```py
label start:

    scene expression Movie(play="oa4_launch.webm")

    "A"

    "B"

    scene black

    "C"

    "D"

    return
```
advance to "D" and then roll back to "B". there is no movie playing with Ren'Py 8.3 and 8.4, 8.2 works fine though.
