### ISSUE TITLE
Viewport draggable doesn't work inside a drag since 8.2

### ISSUE THREAD

**Issue by Kiaazad** [renpy/renpy#5776]
Looks like something with drags has changed recently that steals drag events from viewports inside them.
```python
screen viewport_in_drag:
    drag:
        frame:
            xysize 400,400
            viewport:
                draggable True
                frame:
                    xysize 300,800
                    text "Show a background. This uses a placeholder by default, but you can, Show a background. This uses a placeholder by default, but you can"
```
Trying to drag the viewport will drag the parent drag instead.

**Comment by the66F95** [comment]
setting the `modal` property to `True` of the outer frame containing the viewport should solve your problem.

**Comment by Kiaazad** [comment]
> setting the `modal` property to `True` of the outer frame containing the viewport should solve your problem.

Doesn't that just block interactions to the underlying drag container?
The aim is having them both function as expected. Dragging the viewport when the mouse is in the viewport area, and dragging the drag when the mouse is on the drag area.

**Comment by the66F95** [comment]
indeed. it doesn't fix the issue but allow you to restore the old behavior.
you just have to provide something to grab within the drag. currently the frame containing your viewport is the entire drag.
for example, you could use this:
```py
screen viewport_in_drag():
    drag:
        frame:
            xysize 500, 500
            pos .2, .2

            frame:
                xysize 400, 400
                modal True
                align .5, .5

                viewport:
                    draggable True
                    frame:
                        xysize 300, 800
                        text "Show a background. This uses a placeholder by default, but you can, Show a background. This uses a placeholder by default, but you can"
```

**Comment by the66F95** [comment]
that commit breaks the ability to drag a viewport by grabbing a contained button for instance.
moving the block
```py
        if inside and draggable:

            if renpy.display.behavior.map_event(ev, 'viewport_drag_start'):

                self.drag_position = (x, y)
                self.drag_position_time = st
                self.drag_speed = (0.0, 0.0)

                self.xadjustment.end_animation(instantly=True)
                self.yadjustment.end_animation(instantly=True)

                raise renpy.display.core.IgnoreEvent()
```
back to its old position solves the problem on my end.

**Comment by renpytom** [comment]
Good catch. The actual fix is a bit different, and it should be fixed now.

**Comment by the66F95** [comment]
still not completely.
dragging a bar/slider contained by a viewport now starts dragging the viewport after exceeding `renpy.config.viewport_drag_radius` even if the movement is in the axis of the bar/slider.

**Comment by the66F95** [comment]
i use now this:
```
--- viewport.py	Thu Oct  3 09:39:37 2024
+++ viewport.py	Thu Oct  3 11:11:42 2024
@@ -345 +345 @@
-            if grab is None and renpy.display.behavior.map_event(ev, 'viewport_drag_end'):
+            if (grab is None or (grab is not self and hasattr(grab, "_draggable"))) and renpy.display.behavior.map_event(ev, 'viewport_drag_end'):
@@ -356 +356,3 @@
-                if math.hypot(oldx - x, oldy - y) >= renpy.config.viewport_drag_radius:
+                grabbed = hasattr(grab, "_draggable") and grab.is_focused()
+
+                if (math.hypot(oldx - x, oldy - y) >= renpy.config.viewport_drag_radius) and not grabbed:
```
it fixes also the issue of unintentional dragging the viewport after clicking a contained bar.

**Comment by the66F95** [comment]
one last diff:
```
--- viewport.py	Fri Oct  4 07:33:38 2024
+++ viewport.py	Fri Oct  4 07:51:58 2024
@@ -344 +344 @@
-        if (grab is not None) and getattr(grab, '_draggable', False):
+        if (grab is not None) and getattr(grab, '_draggable', False) and (grab is not self):
@@ -358 +358 @@
-                grabbed = getattr(grab, "_draggable") and grab.is_focused()
+                grabbed = getattr(grab, "_draggable", False) and grab.is_focused()
```

**Comment by renpytom** [comment]
Can you please give unified diffs, with an explanation of what you think the problem is?

**Comment by the66F95** [comment]
changes were made to prevent `self.drag_position` to become `None` and the resulting error if the initial viewport is dragged.
just expand the preferences screen of any project so it becomes draggable. then try to drag it.

**Comment by the66F95** [comment]
but most important, there is a typo in the comment on line 339. 😉

**Comment by Kiaazad** [comment]
Just checked 8.3.4, looks like the clicks don't pass through viewports to trigger buttons in the background anymore. Is there an option to restore that functionality without setting draggable to False?

**Comment by the66F95** [comment]
i doubt this behavior has changed or ever worked like this.
the drag simply gets focus and not anything it might be covering.
even if you click "through" a viewport, the underneath drag should get focus again.

<details>

<summary>tested with Ren'Py 8.0 up to the current nightly with...</summary>

```renpy
screen test():
    add "#888"

    textbutton "Return" at truecenter action Return() text_idle_color "#ccc"
    
    drag:
        align (.1, .1)

        frame:
            idle_background "#a008"
            hover_background "#c008"
            selected_background "#f008"
            xysize (400, 400)
    
    drag:
        align (.9, .1)

        frame:
            idle_background "#0a08"
            hover_background "#0c08"
            selected_background "#0f08"
            xysize (400, 400)
            
            frame:
                idle_background "#00a8"
                hover_background "#00c8"
                selected_background "#00f8"
                align (.5, .5)

                viewport:
                    xfill False
                    ymaximum 300
                    draggable True
                    
                    vbox:
                        for i in range(10):
                            text "TEXT"

label start:
    call screen test
```

</details>

**Comment by the66F95** [comment]
use the current nightly.
your "dismiss" button fires wherever you click, inside or outside of frame 1,  viewport, frame 2 or text.
