### ISSUE TITLE
[SteamDeck] - "always" keyboard_mode breaks the SteamOS user interface.

### ISSUE THREAD

**Issue by ZereoX** [renpy/renpy#5873]
## Description
Ren'Py titles which have their `_renpysteam.keyboard_mode` set to `"always"` will ceaselessly re-invoke the on-screen keyboard when a text input field is present which breaks rendering and steal input away for Steam if you attempt to open the Steam or Quick-Access Menu. This leads to Steam failing to close the on-screen keyboard when opening the Steam or Quick-Access Menu.

### Video
https://github.com/user-attachments/assets/6eb23b5e-868d-4421-a2e1-88681183ff10

#### Steps for reproducing this issue:

1. Launch [Alison Fall of the Apple](https://store.steampowered.com/app/2800530/Alison_Fall_of_the_Apple/).
2. Select **Start**.
3. Skip the next few dialogues and select "I confirm that [...]".
4. Once prompted for "What is your name?", the on-screen keyboard should open.
5. Press <kbd>Steam</kbd> or <kbd>...</kbd> to open the **Steam** or **Quick-Access Menu**.

With any Ren'Py title that opens the on-screen keyboard automatically:
1. Navigate to `<game-install-directory>/renpy/common/`.
2. Open `00steam.py` and edit the value of `keyboard_mode` to `"always"`.
3. Launch the title and proceed into game until you are prompted for input.
4. Once prompted for input, the on-screen keyboard should open.
5. Press <kbd>Steam</kbd> or <kbd>...</kbd> to open the **Steam** or **Quick-Access Menu**.

Reproduction Rate: 5/5

#### Affected Platforms
- LCD: Yes
- OLED: Yes
- Desktop Deck-like session (`gamescope -e -- steam -gamepadui -steamdeck`): Yes
- Desktop: No (OSK does not appear in Big Picture Mode for Ren'Py titles)

#### Steam Deck
| Component | Version |
| --------- | ------- |
| OS        | 3.6.19 / 3.7.0 |
| OS Build  | 20241021.100 / 20240919.1002|
| Kernel    | 6.5.0.valve22 / 6.8.12.valve2|
| BIOS      | F7A0131 (LCD) / F7G0112 (OLED) |
| Steam     | 1726683985 (Stable) / 1729917543 (Beta)|

#### Actual result
- Opening the Steam or Quick-Access Menu while a title is actively attempting to invoke the on-screen keyboard will 1) break rendering of the Steam user interface 2) steal gamepad focus away from Steam making it impossible to navigate.

#### Expected result
- Ren'Py should avoid re-invoking the on-screen keyboard when the title is no longer in focus. This would match the current behaviour of using the **Show Keyboard** shortcut (<kbd>Steam</kbd> + <kbd>X</kbd>) where it only works if you are actively in-game.

#### Notes
- A related issue has also been filled on the steam-for-linux github: https://github.com/ValveSoftware/steam-for-linux/issues/11404

**Comment by renpytom** [comment]
I believe this has been fixed for quite some time, as the default keyboard mode is now "once", and not "always".

**Comment by ZereoX** [comment]
> I believe this has been fixed for quite some time, as the default keyboard mode is now "once", and not "always".

You are right, I should have looked it up first. The default was changed here: https://github.com/renpy/renpy/commit/9cde14fa6dc4f1a9da8ebe94ff5a95e462f6ccec

I guess we're mostly still seeing new release or updates with out-of-date Ren'Py versions or the dev having manually changed the option to "always". 

Is there an expectation that the "always" keyboard mode will be deprecated in the future? I noticed it was still the first option in the Steam Deck reference guide: https://github.com/renpy/steam-deck-guide?tab=readme-ov-file#renpy-750-or-later.
