### ISSUE TITLE
Audio Fadeout Prevents Movie From Looping

### ISSUE THREAD

**Issue by OsirianGames** [renpy/renpy#5887]
When adding a movie displayable and audio to a custom channel at the same time, the fadeout of prexisting audio on that channel prevents the movie displayable from looping. I was able to isolate the environment to reproduce the bug and have attached the project which shows the issue from the start label. WARNING: The project movies are NSFW.

Some notes about the bug:
- Only affects custom registered audio channels
- Only an issue when movies and audio are played together (having a 0.1s pause statement between the two is my current workaround)

[Project Download (NSFW) 39MB](https://mega.nz/file/Un9S1YpJ#9KxQiWKdBVaExQ6aia9dLQwI88CCzuGPW85WL6XYh58)

**Comment by OsirianGames** [comment]
Found the offending line of code in the video.py file.
`renpy.audio.music.play(new._play, channel=new.channel, loop=new.loop, synchro_start=True)`

When synchro_start is set to False, the issue is resolved. I haven't had time to look into the code to see what's going on here, but my quick assumption is the movie file is trying to synchronize with the sound and movie channel to play together even though they shouldn't be associated with each other at all.

**Comment by renpytom** [comment]
I believe this was already fixed on the nightly fix branch.

**Comment by OsirianGames** [comment]
Just gave the test project and my actual project a test with the nightly build and am still encountering this issue there.
